### ISSUE TITLE
Local server - adding printer fails

### ISSUE THREAD

**Issue by mplogas** [TheSpaghettiDetective/TheSpaghettiDetective#103]
**System:**

TheSpaghettiDetective: latest from master
Docker: 19.03.1
Docker-Compose: 1.24.1
OS: Debian 9
Kernel: 4.15.18 x64

**Description:**

Adding a printer seems pretty straight forward, but the "current print" field is required - which is only an empty field for me. Thus adding my printer (and an auth token) isn't possible.

**Expected behaviour:**

Since there can't be any "current print" when adding the first printer to the system, I was expecting this field NOT to be mandatory and therefore allwoing me to set up the first printer.

**Steps to reproduce**

1. Set up TheSpaghettiDetective on-premise, according to the documentation (using docker etc)
2. Set up a user and a site.
3. Set up the first printer.
	a. put in name
	b. select user from dropdown
	c. create an auth token
	d. hit save
	e. an error message appears

![25-10-_2019_10-19-01](https://user-images.githubusercontent.com/842121/67556383-5ab8a380-f713-11e9-852c-0d138a311f6d.png)

**Comment by kennethjiang** [comment]
It's strange. [`current_print` is not a required field in the model](https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/blob/master/web/app/models.py#L128).

In any case, you can (actually are supposed to) create a printer from the normal user interface at http://yourserver:3334/printers/. Is there a reason why it is not an option for you?

**Comment by mplogas** [comment]
@kennethjiang regarding `current_print` it's still that issue when going through the django admin site. I did not knew about the regular interface, this works very well. Thanks!

**Comment by kennethjiang** [comment]
Great. Thank you for confirming that!
