### ISSUE TITLE
Self-hosted TSD, cannot connect on same LAN. 

### ISSUE THREAD

**Issue by jterranella** [TheSpaghettiDetective/TheSpaghettiDetective#104]
I have my SD server up and running. I tried connecting Octoprint to it and I get the connection error, make sure your connected to the internet, yada yada.

Went over to the Pi and verified that it can hit the net AND that it could ping the SD server. I used the curl command and it returned no errors. 

Not sure what's going on at this point. I can't get the two to communicate, but they see each other from the shell.

**Comment by kennethjiang** [comment]
Can you go to our discord channel https://discordapp.com/invite/NcZkQfj and ask the question there? There are more people there who can help you, and you will get faster response.
