### ISSUE TITLE
Add build option to disable sign-up on private server

### ISSUE THREAD

**Issue by RaymondHimle** [TheSpaghettiDetective/TheSpaghettiDetective#133]
Self explanatory. Allow public facing private servers to disable user signup. Can help reduce the number of fake accounts made on private servers.

**Comment by t413** [comment]
+1 for this!

In the interim I added a haproxy rule to my frontend that disables the registration page: (which is also the _form submission endpoint_, importantly)

`use_backend dummy-backend if { path_beg /accounts/signup }`

I had to add a backend with no server called _dummy-backend_ as well. Works great! I'm sure there's an equivalent way using nginx (but for my small setup I'm sticking with what I've configured before 😅)
