### ISSUE TITLE
Not actively watching

### ISSUE THREAD

**Issue by ChadOhman** [TheSpaghettiDetective/TheSpaghettiDetective#135]
Hi all -

I've followed the directions in the readme to set up the detective however I'm getting "The Detective Is Not Watching (Why?)"

The site address is correct, the plugin says it's connected. I'm getting an image on the 3334 interface.

What am I doing wrong here?

Thanks.

**Comment by kennethjiang** [comment]
Are you using TSD cloud (https://www.thespaghettidetective.com/) or your own private server? @ChadOhman

**Comment by ChadOhman** [comment]
Oops, sorry, I should have indicated. My own private server. Ubuntu Server 18.04 with the latest docker/docker-compose.

Thanks

**Comment by RaymondHimle** [comment]
Give the Octoprint device a full restart (OS level.) This fixes the issue in some cases.

**Comment by ChadOhman** [comment]
That worked, thank you!

**Comment by kennethjiang** [comment]
Thank you @RaymondHimle for helping out here. Do you know why an OS-level restart will fix it?

**Comment by RaymondHimle** [comment]
No I don't know why. But a restart seems to fix a lot of issues here. An OS restart might not have been required for this issue but it doesn't hurt.
