### ISSUE TITLE
Printer connected but no webcam stream on TSD web interface

### ISSUE THREAD

**Issue by PedroC1999** [TheSpaghettiDetective/TheSpaghettiDetective#148]
I have setup TSD as per the instructions in the README.
The printer is communicating with TDS, and I can see temperatures/progress etc on the interface.
The server is not local to my network, but the secret tests are valid.
Within OctoPrint, I can see the webcam feed fine. The camera is setup using MotionEye.
In TDS, I simply see a black screen as show below.

![image](https://user-images.githubusercontent.com/21296411/71608278-f3d2c300-2b77-11ea-965a-85c9558e4ee8.png)

I am able to provide any logs or debug anything if required,
Many thanks!

**Comment by kennethjiang** [comment]
@PedroC1999 Just want to check if you closed it because the problem was fixed? If so, can you let me know what you did to fix it?

**Comment by PedroC1999** [comment]
The issue was in the "Site" setup. I had used the Octoprint Servers IP instead of the TSD IP. 

This could possibly be added to the FAQ on the TSD website for the "no webcam stream" section. 

Many thanks!

**Comment by kennethjiang** [comment]
Gotcha! It's a really good suggestion to add this to the instructions!
