### ISSUE TITLE
Question about Django Page

### ISSUE THREAD

**Issue by yeongbenny** [TheSpaghettiDetective/TheSpaghettiDetective#150]
Hello,
I was following the server setup instruction
I got to start sudo 'docker-compose up -d'
and I can see port 3334 is opened, but there is no way I can
access to Django website :(

I am using Ubuntu on Google Cloud Platform

Thank you!

**Comment by RaymondHimle** [comment]
You likely need to modify ingress rules. See this stackoverflow answer https://stackoverflow.com/a/21068402

**Comment by yeongbenny** [comment]
@RaymondHimle Thank you!! 👍

**Comment by RaymondHimle** [comment]
@kennethjiang This issue can be closed

**Comment by kennethjiang** [comment]
Thank you @RaymondHimle !
