### ISSUE TITLE
Detective not watching

### ISSUE THREAD

**Issue by krackware** [TheSpaghettiDetective/TheSpaghettiDetective#156]
![Screen Shot 2020-01-20 at 7 18 17 AM](https://user-images.githubusercontent.com/60107455/72741887-0deb3a00-3b55-11ea-8e90-4ac733e15888.png)

I just installed The Spaghetti Detective on my Ubuntu server.  The connection to octoprint works fine and the majority of the setup was uneventful.  

However, when the software runs, it warns that the detective is not watching (see attached).  It appears that it may be asking for me to purchase time (hourglass icon top right).  But there is no way to do this for a home server.  Any ideas?

**Comment by RaymondHimle** [comment]
Best place to get responsive help for TSD is on the TSD Discord https://discord.gg/hsMwGpD

**Comment by RaymondHimle** [comment]
@kennethjiang You can close this due to inactivity
