### ISSUE TITLE
Email Testing Feature for Stand Alone Server

### ISSUE THREAD

**Issue by jreed1701** [TheSpaghettiDetective/TheSpaghettiDetective#166]
Issue:
In the context of the stand alone server, there is no method available via command or user interface to validate that the email settings in the [docker-compose.yml](https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/blob/master/docker-compose.yml) file are working.  One must initiate a print, simulate a spaghettification, and hope that an email is sent. 

Add a feature to allow a user of the stand alone server to test email configuration. The system shall send a test feature upon activation/initiation using the EMAIL-* under environment in the reference yaml file. 

Reference:
 [docker-compose.yml](https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/blob/master/docker-compose.yml) 

Relates to #129 a need for configuration testing.

**Comment by kennethjiang** [comment]
Before this issue is solved, a work around is

- Make sure `Notify me when print job is canceled` is checked in `Preferences` page.
- Start a test print job and cancel it.
- Wait for the email to arrive (or not)

**Comment by jreed1701** [comment]
@kennethjiang Hi. Sorry to take so long to try this. I did and it did not work. I've got my setting in correctly for sure.  I followed the procedure you suggested but no email.

Furthermore, since this issue card was created the user preferences page has a Verify Email setting. When I click "Re-send Verification" I get a 500 server error. This corroborates the the system is unable to send the email.  

Exact Route; http://IP_ADDR:3334/accounts/email/

I will say, I am using a gmail account with 2FA enabled. Would that cause any issues?

Screen shot for good measure:

![image](https://user-images.githubusercontent.com/11220408/80314638-a4687080-87c0-11ea-9eb5-0f74281e6251.png)

**Comment by kennethjiang** [comment]
Yeah SMTP server is a thorny thing. We are paying for AWS SES to get email delivered which is quite reliable.

Please join our private server discord channel at: https://discord.gg/UFH3JC. Hopefully you can find help there

**Comment by handsome1987** [comment]
I have the same problem als below.
Does anyone how to fix this?

> @kennethjiang Hi. Sorry to take so long to try this. I did and it did not work. I've got my setting in correctly for sure. I followed the procedure you suggested but no email.
> 
> Furthermore, since this issue card was created the user preferences page has a Verify Email setting. When I click "Re-send Verification" I get a 500 server error. This corroborates the the system is unable to send the email.
> 
> Exact Route; http://IP_ADDR:3334/accounts/email/
> 
> I will say, I am using a gmail account with 2FA enabled. Would that cause any issues?
> 
> Screen shot for good measure:
> 

> ![image](https://user-images.githubusercontent.com/11220408/80314638-a4687080-87c0-11ea-9eb5-0f74281e6251.png)

**Comment by jagr200** [comment]
> I have the same problem als below.
> Does anyone how to fix this?
> 
> > @kennethjiang Hi. Sorry to take so long to try this. I did and it did not work. I've got my setting in correctly for sure. I followed the procedure you suggested but no email.
> > Furthermore, since this issue card was created the user preferences page has a Verify Email setting. When I click "Re-send Verification" I get a 500 server error. This corroborates the the system is unable to send the email.
> > Exact Route; http://IP_ADDR:3334/accounts/email/
> > I will say, I am using a gmail account with 2FA enabled. Would that cause any issues?
> > Screen shot for good measure:
> 
> > ![image](https://user-images.githubusercontent.com/11220408/80314638-a4687080-87c0-11ea-9eb5-0f74281e6251.png)

Yes. Change the settings in the file and then rebuild the container using run "sudo docker-compose up --build -d"

**Comment by goeland86** [comment]
I managed to get the email verification going. With 2FA on Gmail you need to create an application password that you feed to docker-compose.

What I'm having an issue with is that I got the verification email, but I did not receive any of the job completed or job failed emails I was expecting to receive...

**Comment by RaymondHimle** [comment]
This would be a separate issue. However I have noticed this as well and it seems to be a bug. What platform are you running the TSD server on?

**Comment by goeland86** [comment]
Ubuntu 20.04 with latest docker-ce.

**Comment by goeland86** [comment]
I'm happy to open a separate issue if that helps.

**Comment by RaymondHimle** [comment]
X86 or arm?

**Comment by goeland86** [comment]
x86 - it's my workshop Intel NUC. Not super powered, but I do have 16GB of ram and 4 logical cores (2 with HT)

**Comment by kennethjiang** [comment]
See https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/blob/master/docs/email_guide.md
