### ISSUE TITLE
Doesn’t pause on failure

### ISSUE THREAD

**Issue by joachimvenaas** [TheSpaghettiDetective/TheSpaghettiDetective#173]
My setup (win10 docker) doesn’t pause on failures. any tips and tricks?

- I can pause from the webinterface. 
- I haven’t got the the gmail setup working yet

**Comment by joachimvenaas** [comment]
I got the mail notifications to work, and then the print paused upon a simulated failure

**Comment by kennethjiang** [comment]
Glad you figured this out!

Do you mind sharing the cause of the problem and how you fixed it? It'll benefit other users who land on this issue when they search for similar problems.

**Comment by joachimvenaas** [comment]
i couldn’t get gmail working, so i used amazon simple email service. And i was a little more patient with the spaghetti test, took a couple of minutes before the print paused
