### ISSUE TITLE
default octoprint view: thespaghettidetective is loading youtube (and subsequently doubleclick)

### ISSUE THREAD

**Issue by Mirarkitty** [TheSpaghettiDetective/TheSpaghettiDetective#180]
Tracing a spurious 

_Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://googleads.g.doubleclick.net/pagead/id. (Reason: CORS request did not succeed)._

I find that this URL is loaded by the default Octoprint interface (early, too):
https://www.youtube.com/embed/ZpDw9mNBngU

Would it be possible to only access third party sites on request?

**Comment by RaymondHimle** [comment]
See https://github.com/TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective/issues/51#issuecomment-589490327

**Comment by kennethjiang** [comment]
Thank you @RaymondHimle for chiming in.

@Mirarkitty I'm not attached to YouTube. Just wanted to put a video somewhere visible to help users understand what TSD is. Will be happy to merge your PR if you can figure out another way to do it.

**Comment by Mirarkitty** [comment]
Maybe a video link would be enough instead of an embedded video? Not sure why it loads in the default interface, before everything else, because it certainly doesn't display there.

**Comment by Mirarkitty** [comment]
![Screenshot from 2020-03-21 04-52-56](https://user-images.githubusercontent.com/3462581/77218840-071a7c80-6b30-11ea-9762-fac26da9765d.png)
![Screenshot from 2020-03-21 04-51-40](https://user-images.githubusercontent.com/3462581/77218841-084ba980-6b30-11ea-8cf1-ec951d4198b4.png)

**Comment by kennethjiang** [comment]
This is how OctoPrint works - it loads every links from itself all at once, even if some pages/tabs are not being displayed. For instance, you can see that it's loading "slicing", even if you are not using slicer on it at all.

**Comment by justinmbrock** [comment]
Just installed this. And now I'm uninstalling it. Thanks anyway, but I don't need iframes loading your trackers in the background.

**Comment by Mirarkitty** [comment]
I'm also pretty sure blaming Octoprint for loading trackers is not a way forward.

**Comment by kennethjiang** [comment]
Closing since this is more a philosophical debate than a bug.

**Comment by Mirarkitty** [comment]
Wait, forcing a load of a tracker is a philosophical debate? Good to know where you stand.
