### ISSUE TITLE
Web/Tasks not working - ModuleNotFoundError: No module named 'config' and manage.py

### ISSUE THREAD

**Issue by thorgod** [TheSpaghettiDetective/TheSpaghettiDetective#186]
Web & Tasks keeps restarting running docker locally. 

![image](https://user-images.githubusercontent.com/13910170/77986536-2fdb0880-72cc-11ea-964e-48f8c30c0d2f.png)

Tasks
docker-compose logs -f tasks

![image](https://user-images.githubusercontent.com/13910170/77986493-11750d00-72cc-11ea-8a5c-7f9d63283440.png)

**Comment by thorgod** [comment]
Here is the web. 
docker-compose logs -f web

![image](https://user-images.githubusercontent.com/13910170/77986916-2b631f80-72cd-11ea-909d-b408753f9eaa.png)

**Comment by kennethjiang** [comment]
Please run `docker-compose exec web sh`, and you will be dropped into a shell. In that shell, please run the follow commands and post the output here (please use copy/past, not screenshots):

`pwd`
`pip list`

**Comment by thorgod** [comment]
I cant even get into shell before it restarts. Maybe its because I am running a windows 7, looking at the video it sounds like you need windows 10?

![image](https://user-images.githubusercontent.com/13910170/78050093-add0fb00-7330-11ea-9fb7-912b87b7813e.png)

**Comment by RaymondHimle** [comment]
Sounds like the app resources are not in the container. Can you rebuild the container with ```docker-compose --build -d```

**Comment by thorgod** [comment]
@RaymondHimle 
I assume you mean  `docker-compose up --build -d` because  `docker-compose --build -d` gives me the help options


(Text https://pastebin.com/kZF3GLDb)
![image](https://user-images.githubusercontent.com/13910170/78054428-ea075a00-7336-11ea-8038-3f4e5b47218e.png)

**Comment by thorgod** [comment]
Its ok I just created a docker image on AWS Cloud and it there no problems. I was just hoping to run it locally first.
