### ISSUE TITLE
traefik not working

### ISSUE THREAD

**Issue by Judoguy12** [TheSpaghettiDetective/TheSpaghettiDetective#189]
On my private server i am unable to to get traefik to work, can i have some advice on what should be used for your domain in the linked guide? https://www.digitalocean.com/community/tutorials/how-to-use-traefik-as-a-reverse-proxy-for-docker-containers-on-debian-9

**Comment by kennethjiang** [comment]
Please come to our discord channel for issues like this: https://discord.gg/ukTmGV

I'm closing this issue now. If you have reason to believe this is indeed caused by a bug, you can reopen it.
