### ISSUE TITLE
getting "Server Error (500)" for any page other than the /admin address after configuration.

### ISSUE THREAD

**Issue by lukeglazebrook** [TheSpaghettiDetective/TheSpaghettiDetective#205]
Installed TSD fine a few times on Ubuntu blew the container and everything away and started fresh.  After the initial config I am now getting "Server Error (500)" for all sites excluding the /admin page.  I have even gone to the extent of rebuilding with a freh Ubuntu box, reinstalling Docker etc and TSD with the same results.  Has something changed?  Feel free to educate me if I am doing something stupid.

**Comment by lukeglazebrook** [comment]
Obviously configured the sites page, any idea where the logs are that I need to examine?

![image](https://user-images.githubusercontent.com/38556084/83950131-2a47f480-a820-11ea-8817-5cd0330e0907.png)

**Comment by lukeglazebrook** [comment]
Sad times ...

![image](https://user-images.githubusercontent.com/38556084/83950142-464b9600-a820-11ea-9823-34d9f1a62b57.png)

**Comment by kennethjiang** [comment]
@lukeglazebrook Can you run `docker-compose logs web` and look for exceptions in the output?

**Comment by kennethjiang** [comment]
@lukeglazebrook Just pushed a commit. Can you do `git pull && docker-compose restart` and let me know if you are still getting 500 errors?

**Comment by matzebecker** [comment]
I had the same issue like @lukeglazebrook and your last commit solved the problem for me, @kennethjiang! Thanks!

**Comment by kennethjiang** [comment]
Awesome! Will close the issue now.

**Comment by lukeglazebrook** [comment]
Well done Ken mate you fixed it, didn't even need a restart.  I must say I have never used this Github thingy I think its got some real potential to take off big

**Comment by war3zlod3r** [comment]
having this same issue I can only access the pages from localhost, 127.0.0.1 or my local ip won't work and return error 500

**Comment by cdvankammen** [comment]
this seems to be an issue I am still getting and have tried everything under the sun with docker web commands. Any thoughts on why this is not accessbile from outside of local host?
