### ISSUE TITLE
Temp Files not being deleted

### ISSUE THREAD

**Issue by dkggpeters** [TheSpaghettiDetective/TheSpaghettiDetective#215]
I get jpg files that accumulate in /TheSpaghettiDetective/web/static_build/media/tsd-pics/raw and fill up the SD Card and eventually force the Spaghetti Detective to not work.  I cleared these files and it appears they are also in a tmp directories listed below.  After a job is done, aren't these files supposed to clear?  I had to manually delete in order to free up disk space and get  everything working again.

![image](https://user-images.githubusercontent.com/63671969/84295548-b7d55e00-ab18-11ea-868a-3870b8515d7a.png)

**Comment by kennethjiang** [comment]
Ah cool! Can I close this issue now? @dkggpeters

**Comment by dkggpeters** [comment]
So far it appears that that problem no longer exists on the new release.

For further clarification:

I am running this on a Jetson Nano and setup up last week using the instructions on your blog.

**Comment by kennethjiang** [comment]
Ok. I will keep it open for a while. Please keep an eye on this issue and update this issue after a few days.

**Comment by dkggpeters** [comment]
Kenneth,

Yes, It appears to be releasing and deleting the files with the new
release.  The new release appears to stream the video better as well.

Dave

**Comment by dkggpeters** [comment]
Yes,  I will let you know in a few days that all is continuing to go well.

Dave

**Comment by dkggpeters** [comment]
Kenneth,

The files are deleting as they should.

I did have one issue which I believe is on me.  I have the following in my
timelapses in which the files did not delete.  I setup a VPN the other day
and I then ran a longer print job of 26.5 hours on this one printer.  My
other two I ran many jobs of varying lengths with no issues at all.  When I
setup the VPN, I changed my server address to be on the local lan. When I
checked after noticing the files were not deleted, the checkbox for "I have
my own TSD server" was still checked.  I know that after you save the
changes it will become unchecked.  The entire job ran in this state.  I had
to restart Octoprint to clear it.  I believe this is what caused the
issue.

The printer is currently idle and I still have 2.5G in the raw
directories.  Should I just delete the files or is there a way to clear
them and repair the timelapse?  I even did a rebuild and the files remained.

[image: image.png]


[image: image.png]
[image: image.png]

**Comment by kennethjiang** [comment]
The "have own server" checkbox is a known issue - it'll flip to unchecked next time when you reload Octoprint page. It is a user experience issue but it shouldn't cause any functional problems.

The image files will remain if the "print finished" signal is missing, typically because the Pi is disconnected from the server at the time when print finishes. They can be deleted without impacting any part of the system.

One way to check what is causing the files to remain is to check if the corresponding images are deleted after a time-lapse is generated. If a timelapse is generated, and the images that the timelapse is made from are still there, then it is probably a bug.

**Comment by dkggpeters** [comment]
Kenneth,

Thanks for the response. I will keep an eye on it.

It very well may have been a connection issue as the printer that was
running this is way down in the basement with not a very good wifi
connection.

**Comment by RaymondHimle** [comment]
Closing as issue has been resolved
