### ISSUE TITLE
Web_1 keeps restarting

### ISSUE THREAD

**Issue by Tumtum2814** [TheSpaghettiDetective/TheSpaghettiDetective#217]
Trying to setup the detective on windows 10 pro, went smooth, but web_1 keeps restarting.
Getting this from the logs. 
web_1     | standard_init_linux.go:211: exec user process caused "no such file or directory"
web_1     | standard_init_linux.go:211: exec user process caused "no such file or directory"
web_1     | standard_init_linux.go:211: exec user process caused "no such file or directory"
web_1     | standard_init_linux.go:211: exec user process caused "no such file or directory"
web_1     | standard_init_linux.go:211: exec user process caused "no such file or directory"
web_1     | standard_init_linux.go:211: exec user process caused "no such file or directory"
web_1     | standard_init_linux.go:211: exec user process caused "no such file or directory"
web_1     | standard_init_linux.go:211: exec user process caused "no such file or directory"
web_1     | standard_init_linux.go:211: exec user process caused "no such file or directory"
web_1     | standard_init_linux.go:211: exec user process caused "no such file or directory"
web_1     | standard_init_linux.go:211: exec user process caused "no such file or directory"
web_1     | standard_init_linux.go:211: exec user process caused "no such file or directory"
web_1     | standard_init_linux.go:211: exec user process caused "no such file or directory"
web_1     | standard_init_linux.go:211: exec user process caused "no such file or directory"
web_1     | standard_init_linux.go:211: exec user process caused "no such file or directory"
web_1     | standard_init_linux.go:211: exec user process caused "no such file or directory"
web_1     | standard_init_linux.go:211: exec user process caused "no such file or directory"
web_1     | standard_init_linux.go:211: exec user process caused "no such file or directory"

**Comment by kennethjiang** [comment]
Can you attach the full log output for `web` container?

**Comment by Tumtum2814** [comment]
maybe I'm missing something, But it's literally the only message that web outputs for forever.  Both from the Docker Dashboard and from docker-compose logs -f
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"

**Comment by kennethjiang** [comment]
if you run `docker-compose stop` followed by `docker-compose up`, you should get the full output.

**Comment by Tumtum2814** [comment]
[startup log.txt](https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/files/4762491/startup.log.txt)
ah gotcha, lots more to chew on lol. Attached.

**Comment by kennethjiang** [comment]
https://futurestud.io/tutorials/how-to-fix-exec-user-process-caused-no-such-file-or-directory-in-docker

This may be relevant. Although I know most Windows users are able to run it without any problem.

**Comment by Tumtum2814** [comment]
Wow. You are a master. That was the fix. She's up and going now. Thanks so much!
