### ISSUE TITLE
CORS error for private server to download time-lapse

### ISSUE THREAD

**Issue by kennethjiang** [TheSpaghettiDetective/TheSpaghettiDetective#243]
Time-lapse video download is currently broken on private servers since we moved to Vue, due to the CORS issue.

![errors](https://user-images.githubusercontent.com/779786/86401603-632c8b00-bc5f-11ea-95f3-d1618cb07f21.png)

**Comment by kennethjiang** [comment]
I don't remember who report this bug, but I just tried it and I can no longer reproduce it myself. Maybe one of the recent commits fixed it?

@RaymondHimle If you can quickly test it, please do so and let me know. Otherwise I will just close it as non-reproducible.

**Comment by RaymondHimle** [comment]
I cannot reproduce.
