### ISSUE TITLE
192.168.101.22(my internal ip) refused to connect

### ISSUE THREAD

**Issue by CovertPluto** [TheSpaghettiDetective/TheSpaghettiDetective#252]
By going to my IP, it comes up with a tutorial page about docker. When I go to 192.168.x.x:3334/admin, it says that it has refused to connect. I'm running the latest version of docker, I think, and it should work just fine on Windows 10 version 1909. Is there any way of accessing the admin page for django?

**Comment by RaymondHimle** [comment]
This sounds like a configuration issue. Best place for help is the TSD forum (Discord)
