### ISSUE TITLE
Focused Feedback Snapshot Images are Inverted (upside-down) - Not syncing with Octoprint Webcam Settings to Invert Camera

### ISSUE THREAD

**Issue by pssnyder** [TheSpaghettiDetective/TheSpaghettiDetective#257]
Whenever I access the Focused Feedback to review images, they are loading upside down. When my timelapses are captured and the video feed is streaming "live" the camera is oriented correctly, however, the snapshots are inverted. I should mention that I do have my camera settings modified within OctoPrint to invert my camera because I do have it mounted upside down. My streams and timelapses are oriented correctly in OctoPrint because of those settings modifications from the Webcam Settings screen in OctoPrint. I'm assuming this is just a configuration issue when TSD pulls the video feed. It seems to be using the OctoPrint settings for streaming and for the timelapse video however for snapshots it is ignoring any user adjusted camera settings in OctoPrint.

![focused_feedback_webcam_upsidedown](https://user-images.githubusercontent.com/2072916/88431721-e78aad80-cdc8-11ea-89e5-6bd30fbe6a38.JPG)
![focused_feedback_webcam_timelapse_normal](https://user-images.githubusercontent.com/2072916/88432153-acd54500-cdc9-11ea-9da5-5714afc82906.JPG)

**Comment by kennethjiang** [comment]
Good catch. This is definitely something we overlooked.

**Comment by kennethjiang** [comment]
@pssnyder This fix will be pushed to production tomorrow.

**Comment by dweenz** [comment]
was the fix implemented I am getting this also. 04/24/2023

**Comment by kennethjiang** [comment]
@dweenz It sounds like a different issue. Please seek help in our discord server https://obico.io/discord/
