### ISSUE TITLE
Allow Docker support for testing on ARM

### ISSUE THREAD

**Issue by BenchPressesBooks** [TheSpaghettiDetective/TheSpaghettiDetective#267]
I have a new Raspberry Pi 4 4GB, and have been working to try and overclock/experiment with pushing its limits a bit to see what is possible. Could the manifest be updated to allow for installation/testing on linux/arm/v7? I will happily guinea pig this myself and report back with the status/tuning wherever possible.

**Comment by BenchPressesBooks** [comment]
Error seen when attempting to execute compose

`ERROR: Service 'ml_api' failed to build: no matching manifest for linux/arm/v7 in the manifest list entries`

**Comment by RaymondHimle** [comment]
Testing has been done. You would need to increase the Pi 4 performance by at least twice just for the ai to run in a less than acceptable timeframe.
