### ISSUE TITLE
Secret Token don't show up when adding new printer

### ISSUE THREAD

**Issue by Lyan9145** [TheSpaghettiDetective/TheSpaghettiDetective#271]
like this
![image](https://user-images.githubusercontent.com/69847064/90500879-1274e100-e17e-11ea-8408-c1bf0dcc91bd.png)
Does it generate locally or some where else?
or it downloads the script on the internet
My network has some problems and some server is probably not reachable

And the "advanced settings" button also not responding when I clicked it

**Comment by kennethjiang** [comment]
I'm not sure I'm following. Have you followed this guide: https://www.thespaghettidetective.com/docs/octoprint-plugin-setup/ ? if so, on which step did you get stuck or see an error?

**Comment by Lyan9145** [comment]
Sorry I didn't state the problem clearly.
I build a private server, when adding new printer, the secret token doesn't show up and the "copy" button doesn't work

**Comment by kennethjiang** [comment]
Can you post the relevant screenshots for the problems you are getting?

**Comment by Lyan9145** [comment]
![image](https://user-images.githubusercontent.com/69847064/90588071-582cba80-e20d-11ea-8135-630a90825156.png)

**Comment by kennethjiang** [comment]
Where did you get that screenshot from? The new printer page looks like this:

![Screen Shot 2020-08-18 at 8 52 28 PM](https://user-images.githubusercontent.com/779786/90590240-e022ae00-e194-11ea-9705-1db9e964de6e.png)

**Comment by Lyan9145** [comment]
So did I build the version of the server? 
I just followed the guide on the github page :(

**Comment by kennethjiang** [comment]
I hate to tell you do more work but I'm still quite confused about this issue. But can you please provide the step-by-step description to reproduce this error?

**Comment by Lyan9145** [comment]
First git clone `https://github.com/TheSpaghettiDetective/TheSpaghettiDetective.git`
Then I delete the `RUN wget --quiet -O model/model.weights $(cat model/model.weights.url | tr -d '\r')` in ml_api/dockerfile and manually download the model.weight file and put it in ml_api/model folder.(Because the wget is too slow)
![image](https://user-images.githubusercontent.com/69847064/90835120-59312980-e37e-11ea-8eaa-d548b474b2fe.png)

![image](https://user-images.githubusercontent.com/69847064/90835004-25560400-e37e-11ea-86c4-3a53450e1972.png)

Last `docker-compose up -d`
It will run into some network issue like time out or some thing else, retry it for a couple of time and it will success

To configure the server I go to `http://192.168.x.x:3334/admin/`
and change "domain name" to 192.168.x.x:3334

and...
still the same...
I think it most likely to be my environment's issue,

I investigate the `http://192.168.x.x:3334/printers/new/` page source code and found
`<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>`
this javascript(line 311) is unreachable
![image](https://user-images.githubusercontent.com/69847064/90841631-acf83e80-e38f-11ea-8c86-19962d02ab58.png)

**Comment by EuphoricPenguin** [comment]
Couldn't this issue be solved by hosting jQuery locally?

**Comment by kennethjiang** [comment]
In theory we can host jquery on TSD server. but then we may have to host all other js, css, sourcemap etc, as any of them may fail to load from a browser that doesn't have a solid internet connection. Not only will it add more load to our TSD cloud server, but it also slow down the page loading unless we set up a very solid CDN.

My suggestion will be to figure out why the connection to code.jquery.com is not working and fix it.

**Comment by Lyan9145** [comment]
I think there is probably a firewall or something that the internet provider have which is blocking my browser. I don't think they would solve the problem for me.

I tried adding printer manually in the Django admin page, the octoprint plugin can be connected to the server, but it don't shown up in the printer page. I will try to print something tomorrow and see if it works.
![image](https://user-images.githubusercontent.com/69847064/91049653-17d79d00-e650-11ea-9241-1019c71111d9.png)
![image](https://user-images.githubusercontent.com/69847064/91049728-3178e480-e650-11ea-8636-3c2b13d331c3.png)
![image](https://user-images.githubusercontent.com/69847064/91049938-8caad700-e650-11ea-988b-9e38b0ea9bc4.png)

**Comment by tazitoo** [comment]
I had a similar issue - the whole page rendering at once (...no 'Next' buttons...) and nothing populated in the token area.

In firefox, I run several privacy extensions (e.g. ghostery, privacy possum, cookie autodelete, and localcdn).  Things worked as expected when I temporarily disabled them.  Hoping this comment helps others if they run into similar issues.
