### ISSUE TITLE
"Service 'web' failed to build" on Jetson Nano

### ISSUE THREAD

**Issue by amolloy** [TheSpaghettiDetective/TheSpaghettiDetective#292]
Following the [Jetson Nano guide](https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/blob/master/docs/jetson_guide.md), building the web component fails with the error:

```
Building web
Step 1/7 : FROM thespaghettidetective/web:base-1.1
base-1.1: Pulling from thespaghettidetective/web
ERROR: Service 'web' failed to build: no matching manifest for linux/arm64/v8 in the manifest list entries
```

I've attached the complete log for reference. 
[JetsonNanoInstallLog.txt](https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/files/5232021/JetsonNanoInstallLog.txt)

This is my first time working with docker-compose, so hopefully I'm just missing some step. For docker-container.override.yml, I have:

```
-> % cat docker-compose.override.yml 
version: '2.4'

x-web-defaults: &web-defaults
  build:
    dockerfile: Dockerfile.base

services:
  ml_api:
    build:
      context: ml_api
      dockerfile: Dockerfile.aarch64
    environment:
        HAS_GPU: 'True'
    runtime: nvidia

```

Thanks for the help!

**Comment by kennethjiang** [comment]
@RaymondHimle Is it because I messed up something when creating the manifest?

**Comment by amolloy** [comment]
Hi, sorry, I don't mean to be a pest, just wondering if there's been any movement on this? I'd love to get TSD running on my Nano, but I haven't got enough understanding of how it all fits together to be much good at solving it myself. Thanks so much!

**Comment by kennethjiang** [comment]
Sorry for the delay. Apparently I tagged the wrong handle...

@raymondh2 just updated the Jetson guide. @amolloy please follow the updated document at: https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/blob/master/docs/jetson_guide.md ?

**Comment by amolloy** [comment]
Thanks! That did the trick, I've got it working now. I appreciate the help!
