### ISSUE TITLE
Support for multiple cameras Follow-up 

### ISSUE THREAD

**Issue by jimmyli56** [TheSpaghettiDetective/TheSpaghettiDetective#300]
This issue is a follow-up to Issue #98 of the same name. Are there any updates regarding the feature on the roadmap? I am also interested in having the feature in TSD as a better safeguard and redundancy in spaghetti detection.

**Comment by kennethjiang** [comment]
@jimmyli56 can you transfer your comments to #98 so that we can track it in the single place? I'm closing this issue now.
