### ISSUE TITLE
Ender 3v2 false positive

### ISSUE THREAD

**Issue by readeral** [TheSpaghettiDetective/TheSpaghettiDetective#305]
A bit of a specific issue and not easily (if even possible) solved, but the new Ender 3v2 has a grate that has a sort of webbing pattern to it which is tripping up my TSD installation. It's pushed it all the way into failing territory but it thankfully didn't cancel the job before I could switch to notify only! Check out the screenshot ![image](https://user-images.githubusercontent.com/15904136/97440756-fc547f80-197b-11eb-8d5a-e08a25e194d5.png)

This issue can probably be mitigated by moving my camera, but if there's a way to tune the software to recognise the fan shroud that would also be great!

**Comment by kennethjiang** [comment]
Sorry for the delay.

This does seem like a tricky problem. Probably can't be completely solved until the AI model start to recognize it.

For now I guess the only thing is to make sure you flag them as false positives in Focused Feedback. The more such negative training cases we have in our database, the faster the AI will pick it up.

I'll close this issue as this isn't a typical "bug" that we can change code to fix. But feel free to add comment as you see fit.
