### ISSUE TITLE
Server install issues on windows server 2019 standard

### ISSUE THREAD

**Issue by caos901** [TheSpaghettiDetective/TheSpaghettiDetective#309]
hello. 
I am trying to set up a server and I am following the server instructions.  Everything has been working great.  I use git to clone the repository but when i go to the next command (cd TheSpaghettiDetective; docker-compose up -d) It starts building the ml_api but gets an error.  I have followed the instructions with no errors prior to this.  Any insight would be appreciated.  Thank you.  

`WARNING: The DOCKERFILE_VERSION variable is not set. Defaulting to a blank string.
Building ml_api
Step 1/7 : FROM thespaghettidetective/ml_api:base
 ---> 6eaa0374427c
Step 2/7 : WORKDIR /app
 ---> Using cache
 ---> 300455788dda
Step 3/7 : EXPOSE 3333
 ---> Using cache
 ---> 8f962395dd7c
Step 4/7 : ADD . /app
 ---> Using cache
 ---> 134260a361f2
Step 5/7 : RUN pip install --upgrade pip
 ---> Running in d07a9a022710
Collecting pip
  Downloading https://files.pythonhosted.org/packages/cb/28/91f26bd088ce8e22169032100d4260614fc3da435025ff389ef1d396a433/pip-20.2.4-py2.py3-none-any.whl (1.5MB)
Installing collected packages: pip
  Found existing installation: pip 19.0.3
    Uninstalling pip-19.0.3:
      Successfully uninstalled pip-19.0.3
Successfully installed pip-20.2.4

ERROR: Service 'ml_api' failed to build: The command '/bin/sh -c pip install --upgrade pip' returned a non-zero code: 4294967295: failed to shutdown container: container d07a9a022710ad321a9bb6a3ff7bcb2e54633709960d4c0bb513777a508a5e7d encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110): subsequent terminate failed container d07a9a022710ad321a9bb6a3ff7bcb2e54633709960d4c0bb513777a508a5e7d encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110)`

**Comment by kennethjiang** [comment]
This looks like an environment issue, instead of a bug. Your best bet is to post the issue on our discord server: https://discord.gg/PKWZB67n

I'm closing this issue for now. But feel free to re-open it if you believe we need to make some code change to fix this.
