### ISSUE TITLE
Disabling feed sharing does not delete URL to previous feed

### ISSUE THREAD

**Issue by TheConsciousness** [TheSpaghettiDetective/TheSpaghettiDetective#347]
I just noticed when re-enabling my feed sharing, and sharing a newly-generated share_token, that my previous shared feed is still active, but is lacking correct information about the print and the printer.

The old, still active link:
![TSD_OldLink_AnetA8](https://user-images.githubusercontent.com/14192161/104080936-50d86e80-51f9-11eb-8fdb-24249464b15e.png)

The newly-generated and updated link:
![TSD_NewLink](https://user-images.githubusercontent.com/14192161/104080938-53d35f00-51f9-11eb-88dc-0a15dc5c1c24.png)

Any way to destroy the old link? Thanks!

**Edit:**
The old link now shows:
**Not Found**
The requested resource was not found on this server.

So maybe it just takes time!

**Comment by kennethjiang** [comment]
This is a known issue https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/issues/314

To disconnect an active browser immediately after a shareable token is disabled has some technical challenges. But a browser refresh will kick out the session using the old token.

I'll close this issue. Feel free to use https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/issues/314 if you have more comments.
