### ISSUE TITLE
Unable to complete Printer connection to local TSD server

### ISSUE THREAD

**Issue by jeremycruz82** [TheSpaghettiDetective/TheSpaghettiDetective#348]
I have successfully installed the octoprint plugin and was able to connect to the TSD service. However when i setup the local TSD Docker flow and tried adding a printer.... i am unable to complete the setup (i get the message  “waiting for TSD plugin to connect”). Octoprint verifies the token correctly but it never connects. Any ideas?

**Comment by kennethjiang** [comment]
We use github issue only for the identified code defect. To get help faster for a general issue like this, please go to our private server forum: https://discord.gg/eE3QPVTk

I will close this issue now. Feel free to re-open it if it proves to a a code defect.
