### ISSUE TITLE
bind mount failed: /data/compose/7/web

### ISSUE THREAD

**Issue by dukes4** [TheSpaghettiDetective/TheSpaghettiDetective#349]
While I try to deploy the TSD server on an existing docker environment the containers
thespagetthidetective_redis_1 and thespagetthidetective_ml_api_1 start up fine.

But thespagetthidetective_web_1 and thespagetthidetective_tasks_1 fail to start. Portainer shows the following error for both: Failure bind mount failed: '/data/compose/7/web' does not exist

Any hint would be highly appreciates as I'm a Newby on docker

**Comment by kennethjiang** [comment]
We use github issue only for the identified code defect. To get help faster for a general issue like this, please go to our private server forum: https://discord.gg/eE3QPVTk

I will close this issue now. Feel free to re-open it if it proves to a a code defect.
