### ISSUE TITLE
[BUG] Error when trying to run on an M1 Mac Mini

### ISSUE THREAD

**Issue by pdoronila** [TheSpaghettiDetective/TheSpaghettiDetective#354]
**Describe the bug**
```
TheSpaghettiDetective % docker-compose up -d
Creating network "thespaghettidetective_default" with the default driver
Building ml_api
Step 1/7 : FROM thespaghettidetective/ml_api:base
base: Pulling from thespaghettidetective/ml_api
ERROR: Service 'ml_api' failed to build : no matching manifest for linux/arm64/v8 in the manifest list entries
TheSpaghettiDetective %
```

**To Reproduce**
1. cd TheSpaghettiDetective
2. docker-compose up -d

**Hosting environment (please complete the following information):**
 - OS: macOS Big Sir
 - Version 11.1
 - Hardware Mac Mini (M1, 2020)

![Docker Version](https://user-images.githubusercontent.com/2334627/104758344-26b01080-5713-11eb-818e-fe49262a6c7b.png)

**Comment by kennethjiang** [comment]
We don't have a machine to build linux/arm64 image. Help will be appreciated!

**Comment by pdoronila** [comment]
@kennethjiang im willing to help, what do I need to do?

**Comment by kennethjiang** [comment]
You can help us by building the `ml_api` image for linux/arm64/v8 platform, and push it to our repo.

You can send email to me at k@thespaghettidetective.com so that I can give you push access for our docker hub.
