### ISSUE TITLE
got some eror

### ISSUE THREAD

**Issue by bumbifyllan** [TheSpaghettiDetective/TheSpaghettiDetective#355]
i got this when install on unraid 

ERROR: Service 'ml_api' failed to build : The command '/bin/sh -c wget --quiet -O model/model.weights $(cat model/model.weights.url | tr -d '\r')' returned a non-zero code: 137

**Comment by bumbifyllan** [comment]
and (orphan image)

**Comment by kennethjiang** [comment]
This doesn't look like a bug. Please follow the instructions included in the issue template and get help on this issue unless you are sure this is caused by a bug in the code. In that case, please provide more details on how you identified this as a bug.

**Comment by litecactus** [comment]
Did you get this error following the instructions from #192  ?
