### ISSUE TITLE
[BUG] WebHook notifications provide incorrect URL

### ISSUE THREAD

**Issue by gstevenson** [TheSpaghettiDetective/TheSpaghettiDetective#364]
**Describe the bug**
Discord (perhaps others) notifications provide a "Click Here to Examine" URL on the webhook notifications, but the URL appears to assume TSD is installed at the same IP address as the printer.

**To Reproduce**
1. Enable Discord Webhook URL as per documentation
2. Send a print
3. Wait for it to complete
4. Click the "Click here to Examine" URL on the webhook notification

**Screenshots**

![image](https://user-images.githubusercontent.com/2399213/106147707-1b77ce80-6170-11eb-92b6-935c272e4720.png)

![image](https://user-images.githubusercontent.com/2399213/106147734-229edc80-6170-11eb-880e-a80d3e63378d.png)

**Additional context**

I have TSD installed on a server at http://192.168.1.10:3334/printers/, and Octoprint at http://192.168.1.216/.

I'd expect to receive a notification giving me the first URL, but it gives me a URL of 192.168.1.216/printers

**Comment by kennethjiang** [comment]
Hmmm I'm surprised. The server wouldn't know about your octoprint ip address so I'm wondering where that came from.

can you post the site configuration in your django admin console?

**Comment by gstevenson** [comment]
Right you are! Configured wrong in the django console :( 

My apologies
