### ISSUE TITLE
[BUG] Telegram 

### ISSUE THREAD

**Issue by SA7BNT** [TheSpaghettiDetective/TheSpaghettiDetective#365]
<img width="876" alt="Bildschirmfoto 2021-01-30 um 20 39 40" src="https://user-images.githubusercontent.com/35367117/106366330-6abe2a80-633b-11eb-8fbd-f5c0d6ffa4c3.png">

**Comment by kennethjiang** [comment]
We have decided to drop the support for telegram.

Telegram doesn't have a very high adopt in TSD user community. Also their server is unreliable has been a major headache for running TSD server. When we didn't have a mobile app, some users were using Telegram as a stop gap solution to get failures on the phone. But now that TSD mobile app provides much more flexible way to achieve the same purpose.

The last straw for us to finally decide to drop Telegram support is the difficulty to debug Telegram integration. We just ported our user preference page to Vue, our new frontend framework. Multiple channels such as PushBullet, Discord, and Telegram were broken as the result. It was quite easy to debug other channels and fix them. But it took me a lot time and still couldn't start a debugging session with Telegram. It made me painfully realize that Telegram notification has become a "liability", as opposed to an "asset" for us.

If someone is interested in getting Telegram back, [this commit](https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/commit/b7ad6954718318a894db05fa61d255be7a3487a0
) can be used as a basis. I will be happy to merge a PR if it's well tested.
