### ISSUE TITLE
[BUG] Error updating to latest version available in repository

### ISSUE THREAD

**Issue by SirSheik** [TheSpaghettiDetective/TheSpaghettiDetective#368]
**Describe the bug**
I am currently running TSD web version 1.3 (thespaghettidetective/web:base-1.3).
![Captura de pantalla 2021-02-02 a las 17 17 19](https://user-images.githubusercontent.com/31892065/106631659-3d60bf00-657d-11eb-96de-de164918e436.png)

When I try to update and compile the new version to work with the latest version of the Octoprint plugin, I get the following error. 

```
Step 7/7 : RUN wget --quiet -O model/model.weights $(cat model/model.weights.url | tr -d '\r')
 ---> Running in df490e3e3754
ERROR: Service 'ml_api' failed to build : The command '/bin/sh -c wget --quiet -O model/model.weights $(cat model/model.weights.url | tr -d '\r')' returned a non-zero code: 4
```

This error is displayed when downloading new files to an existing folder and to a new folder.

**To Reproduce**
First scenario on an existing folder:
git pull
sudo docker-compose up --build -d
[First scenario output.txt](https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/files/5912760/First.scenario.output.txt)

Second scenario on a new, empty folder:
git clone https://github.com/TheSpaghettiDetective/TheSpaghettiDetective.git
cd TheSpaghettiDetective && sudo docker-compose up -d
[Second scenario output.txt](https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/files/5912759/Second.scenario.output.txt)

**Screenshots**
![Captura de pantalla 2021-02-02 a las 17 36 07](https://user-images.githubusercontent.com/31892065/106631552-28842b80-657d-11eb-86c9-bab983335a5f.png)

**Hosting environment (please complete the following information):**
 - OS: Linux  
 - Version: Ubuntu 20.04.1 LTS GNU/Linux 5.4.0-65-generic x86_64)
 - Hardware: Cloud server (VPS) 4 vCPU Cores / 8 GB RAM

**Additional context**
On previous occasions I was able to update the version following the same steps without errors.
Executing the command in verbose mode also does not give more details of the error
sudo docker-compose --verbose up -d
`Step 7/7 : RUN wget --quiet -O model/model.weights $(cat model/model.weights.url | tr -d '\r')
 ---> Running in c66c7888e430
ERROR: compose.cli.main.main: Service 'ml_api' failed to build : The command '/bin/sh -c wget --quiet -O model/model.weights $(cat model/model.weights.url | tr -d '\r')' returned a non-zero code: 4`

Thank you very much

**Comment by kennethjiang** [comment]
Thank you for the detailed report and sorry for the delay.

To further debug, please copy this hash code from your console:

<img width="825" alt="Screen Shot 2021-02-05 at 5 01 03 AM" src="https://user-images.githubusercontent.com/779786/107037181-94c68100-676f-11eb-96ff-7cec374f8683.png">

Then run these commands using the hash code you grabbed:

<img width="1315" alt="Screen Shot 2021-02-05 at 5 01 18 AM" src="https://user-images.githubusercontent.com/779786/107037246-a90a7e00-676f-11eb-8e01-c675d763539f.png">

Let me know what you see in the last command.

**Comment by SirSheik** [comment]
Hi @kennethjiang 
Thank you very much for your answer and your help.
I executed the command inside the container but after waiting I did not get back any result.
`wget --quiet -O model/model.weights $(cat model/model.weights.url | tr -d '\r')`

This is the output:
```
root@MyCloudServer:~/TheSpaghettiDetective# sudo docker-compose up --build -d
WARNING: The DOCKERFILE_VERSION variable is not set. Defaulting to a blank string.
Building ml_api
Step 1/7 : FROM thespaghettidetective/ml_api:base
 ---> 6eaa0374427c
Step 2/7 : WORKDIR /app
 ---> Using cache
 ---> 857f1af0daac
Step 3/7 : EXPOSE 3333
 ---> Using cache
 ---> 774c04bb4a72
Step 4/7 : ADD . /app
 ---> Using cache
 ---> e458421f5eae
Step 5/7 : RUN pip install --upgrade pip
 ---> Using cache
 ---> 1baffb9402f2
Step 6/7 : RUN pip install -r requirements.txt
 ---> Using cache
 ---> c52adc06d8c7
Step 7/7 : RUN wget --quiet -O model/model.weights $(cat model/model.weights.url | tr -d '\r')
 ---> Running in c29f3b65132f
ERROR: Service 'ml_api' failed to build : The command '/bin/sh -c wget --quiet -O model/model.weights $(cat model/model.weights.url | tr -d '\r')' returned a non-zero code: 4
root@MyCloudServer:~/TheSpaghettiDetective# docker run --rm -it c52adc06d8c7 bash
root@6e327195b2af:/app# ls
Dockerfile  Dockerfile.aarch64  Dockerfile.base  auth.py  bin  lib  model  requirements.txt  requirements_x86_64.txt  scripts  server.py  wsgi.py
root@6e327195b2af:/app# wget --quiet -O model/model.weights $(cat model/model.weights.url | tr -d '\r')
```

**Comment by kennethjiang** [comment]
What did you see after this command?

![Screen Shot 2021-02-05 at 8 20 00 AM](https://user-images.githubusercontent.com/779786/107059739-065ff880-678b-11eb-9c16-e38d51ed26f4.png)

**Comment by SirSheik** [comment]
Hi @kennethjiang 
I'm sorry but the command you say doesn't return any results. It takes a couple of seconds to process but there is no result.
You can see it better with the next screenshot.
![Captura de pantalla 2021-02-05 a las 20 37 05](https://user-images.githubusercontent.com/31892065/107080722-f6c7ca80-67f1-11eb-9f12-ccd7f8ecfa64.png)

**Comment by kennethjiang** [comment]
Quite strange. it looks like the wget command actually succeeded.

Please run these commands so that I can dig in more.

<img width="874" alt="Screen Shot 2021-02-05 at 12 16 37 PM" src="https://user-images.githubusercontent.com/779786/107084574-150ad780-67ac-11eb-96f4-b9c3a0d15782.png">

**Comment by SirSheik** [comment]
It returns the value 4

```
root@a0bf02f87c21:/app# wget --quiet -O model/model.weights $(cat model/model.weights.url | tr -d '\r') echo $?
root@a0bf02f87c21:/app# echo $?
4
```
As the value that displays the error during build progress.
![Captura de pantalla 2021-02-05 a las 21 51 25](https://user-images.githubusercontent.com/31892065/107087835-59be5f00-67fc-11eb-8233-0e3b93422ff2.png)

**Comment by kennethjiang** [comment]
Sorry have been out in the past 2 days.

It looks like the wget command was not successful. please run `wget -O model/model.weights $(cat model/model.weights.url | tr -d '\r')` instead.

**Comment by SirSheik** [comment]
Thank you very much, thanks to your last test I detected that there was some connection problem inside the container. After researching and testing, the problem was that my firewall rules did not include the "bridge" network which seems to be temporarily used by the container during the build process.
After solving the network problem everything compiled fine.
Thank you again for your time and help.
