### ISSUE TITLE
Octoprint says everything works correct but my website says OctoPrint is not powered on, or is offline. 

### ISSUE THREAD

**Issue by xTimoDEx** [TheSpaghettiDetective/TheSpaghettiDetective#371]
Hello i sucessfully installed TSD in a Ubuntu VM. I sucessfuly can connect my octoprint with my own website evrything works so when i type in the verification code it connects succesfully in octoprint and also on my own tsd website. Troubleshooting site on octoprint says everything works correctly but my site says OctoPrint is not powered on, or is offline. 

Anyone has a Idea?

 And yes im currently printing so TSD normally should run.

![octopi](https://user-images.githubusercontent.com/20744607/107130770-2d284700-68d1-11eb-8da7-6971525f6ec9.PNG)
![tsd](https://user-images.githubusercontent.com/20744607/107130773-31546480-68d1-11eb-855c-489511005820.PNG)

**Comment by kennethjiang** [comment]
Please ask this question on our discord server first. You will get help faster that way.
