### ISSUE TITLE
enable sign up

### ISSUE THREAD

**Issue by bumbifyllan** [TheSpaghettiDetective/TheSpaghettiDetective#372]
how to enable sign up options ? 
![11111111111111111111](https://user-images.githubusercontent.com/70781203/107133883-1bed3380-68ed-11eb-8827-2defafbcd6c2.JPG)

**Comment by kennethjiang** [comment]
https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/blob/master/docker-compose.yml#L26

Also this is a question, not an issue. Please take questions like this to our discord server instead of opening an issue here.
