### ISSUE TITLE
[BUG] Telegram Bot issue

### ISSUE THREAD

**Issue by TaloniumSW** [TheSpaghettiDetective/TheSpaghettiDetective#377]
**Describe the bug**
When you link your Telegram account, it will not let you do a test notification. 

**To Reproduce**
1. Link your Telegram account
2. Send a test notification
3. Error

**Screenshots**
![Screenshot_60](https://user-images.githubusercontent.com/19256593/107866615-b646fd00-6e40-11eb-9e9b-be872da5047d.png)

**Additional context**
Telegram requires you to send a message to the bot first before it can send a message back to you

**Comment by ajdavids** [comment]
I'll take this one - the fix is to make sure that, when someone links their telegram account, we link them to https://t.me/thespaghettidetective_bot and instruct them to send a message, or we embed a button to send a message to the bot. The user must initiate bot contact.
