### ISSUE TITLE
Explain minimum requirements

### ISSUE THREAD

**Issue by arthurlutz** [TheSpaghettiDetective/TheSpaghettiDetective#38]
First off kudos for a great looking project :tada: 

It would be nice to have some indication of the hardware needed to run this server side bit. I believe CUDA only runs on specific hardware, and seeing the nvidia docker image, I guess you need an NVIDIA card. 

Am a bit of a newbie on the subject, but would this project run on a low-end Nvidia Jetson Nano Developer Kit (99$) https://www.sparkfun.com/products/15297 

I think it might be a great project for tinkerers (into 3D printing) that want to look into machine learning and image processing. Thanks for sharing :open_hands: :clap:

**Comment by kennethjiang** [comment]
Yes we will add documents for the minimum server requirements (once we figure that out ourselves).

Long story short - you don't even need a GPU server to run it. A PC, even an old one, will work just fine unless you want to support more than a handful of printers.

**Comment by pattonwebz** [comment]
I too am interested in these requirements. Bandwidth expectations outgoing from the printer is something I'm keen to know.

I'm planning to run only a single printer and would like to host this in an existing docker swarm. I expect that once the training has been run that the actual CPU requirements are going to be fairly small?

I'm also interested in running it on an addition RPi (I see the documentation text saying that RPi wouldn't be powerful enough to run the learning models... but I actually don't mind waiting several days ;) )

**Comment by kennethjiang** [comment]
What I meant in the previous comment was about predicting, not training. There is no way to train current model without a GPU.

I don't think there is a chance to run the server on a Pi without substantially simplifying the model (see #21). But we will love to see someone figure this out because not requiring a PC would remove a big hurtle for people who want to adopt this project.

**Comment by lukeslaboratory** [comment]
Could this run on a more powerful variant of a Pi? I have an XU4 which is a big.LITTLE ARM octocore. [https://www.samsung.com/semiconductor/minisite/exynos/products/mobileprocessor/exynos-5-octa-5422/](url) I understand that there aren't many more users that would have this versus a full-blown PC floating around, but there are more powerful little boards out there.

**Comment by pattonwebz** [comment]
> What I meant in the previous comment was about predicting, not training. There is no way to train current model without a GPU.
> 
> I don't think there is a chance to run the server on a Pi without substantially simplifying the model (see #21). But we will love to see someone figure this out because not requiring a PC would remove a big hurtle for people who want to adopt this project.

I understand now - existing learning models require things that a humble Pi cannot do. Thanks for the reply, sorry I missed it before now.

I am still quite interested in system requirements once people have tested and reported those. I have not yet tried running the server component on my own (client side is running good though and does indeed spot possible failures so good job!).

**Comment by kennethjiang** [comment]
@lukeslaboratory Good point about these not-so-popular but powerful single board computers. 

Since in our testing a mediocre PC has way more CPU juice than what's needed to support 1 printer, I'm hopeful that these single board computers, although less powerful than a full-blown PC, will be good enough. Will love to see how people get creative to leverage these hardwares.

@pattonwebz Great to hear you are getting some good results with TSD. :)

**Comment by lukeslaboratory** [comment]
@kennethjiang if you ever feel like writing something that could run on a core or two of one of these boards let me know and i'll throw it on my existing NAS that is running on an XU4. I also have an odroid C2 (quad-core 64bit) that I can definitely devote to full-time testing.
![20190414_095012](https://user-images.githubusercontent.com/47956552/56094694-5e818880-5e9b-11e9-9a5e-ff541f377a0c.jpg)
![20190414_095018](https://user-images.githubusercontent.com/47956552/56094701-604b4c00-5e9b-11e9-9472-2fa01128ff1a.jpg)

**Comment by pattonwebz** [comment]
@kennethjiang that looks cool, did you design and print that XU4 case yourself? I had a friend that was looking for something along those lines but never quite found what he needed on amazon lol

**Comment by kennethjiang** [comment]
@pattonwebz you gave credits to the wrong person. ;)

**Comment by lukeslaboratory** [comment]
@pattonwebz - Feel free to give this print a spin. [https://www.thingiverse.com/thing:3563809](url)
I'm the creator.

**Comment by pattonwebz** [comment]
Ha! apologies for pinging the wrong person (and polluting this thread). I blame lack of sleep and long work days XD

I sent the case link to my friend, thanks for sharing that Luke :)

**Comment by andrelec1** [comment]
I just came out of a meeting at work where we talked about the use of a nvidia jetson for an internal IOT project ...

I directly think  to replace my Raspberry by one of these little beast to control my printer, and why not turn TSD directly into it  ...

Some One have try ?

**Comment by vr6syncro** [comment]
anything new from here? have a odroid c2 or rock64 to test.

**Comment by pattonwebz** [comment]
I assume the release of the pi4 with the faster CPU and 4GB memory still is not enough to run the training models?

**Comment by kennethjiang** [comment]
I'm pretty sure Pi4 is still not enough. For other single-board computers, especially the ones with a beefy GPU, you will have to try to be sure.

**Comment by kennethjiang** [comment]
Closing it as `README.md` has been updated with minimum hardware requirements. For anyone who is using single board computer like Jetson Nano, our Discord chat room https://discord.gg/NcZkQfj is a good place to get help/share info.
