### ISSUE TITLE
Jetson Nano RAM Requirements

### ISSUE THREAD

**Issue by cchaz003** [TheSpaghettiDetective/TheSpaghettiDetective#382]
Hi, I'm sorry if this has been answered somewhere else but I tried my hand at google-fu and searching this repo and havent found a concrete answer. I see that the minimum specs for this project say 2gb ram on an old computer but does that apply for the Jetson Nano as well or should I opt for the 4gb model? It's a $30 difference between the two on Amazon so if I can get away with the 2gb model that would be cool.

Thanks!
~Charlie

**Comment by kennethjiang** [comment]
This is a question better suited for our discord forum: https://discord.gg/j4X8dQHd , instead of a code issue.
