### ISSUE TITLE
[BUG] Docker still ignoring Override .yml for Jetson Nano 2GB

### ISSUE THREAD

**Issue by Ethycs** [TheSpaghettiDetective/TheSpaghettiDetective#389]
**Describe the bug**
Documentation between the github and https://www.thespaghettidetective.com/blog/2020/04/19/jetson-nano-spaghetti-detective-guide/ still does not match up.

**To Reproduce**
1. Examine the GitHub Docker Readme
2. Attempt to follow the instructions on the Github jetson link

Note that instructions in 
https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/blob/master/docs/jetson_guide.md
break because `docker-compose.override.yml` is not honored

 - OS:  Ubuntu 18.04.5 LTS
 - Hardware Jetson Nano 2GB
 
Please clarify this issue for GitHub side documentation.

**Comment by kennethjiang** [comment]
Sorry for the delay!

I don't have a Nano (probably it's the time to get one!). So I'll leave @LyricPants66133 or @raymondh2 to comment on this issue.

**Comment by raymondh2** [comment]
I'll look into this but the 2gb nano is not supported due to the ram being shared with the gpu

**Comment by Ethycs** [comment]
Would be great to have that listed somewhere, I grabbed a Jetson for the sole purpose of TSD.

**Comment by raymondh2** [comment]
https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/blob/master/docs/jetson_guide.md

**Comment by Ethycs** [comment]
> https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/blob/master/docs/jetson_guide.md

Productive contribution

https://github.com/TheSpaghettiDetective/TheSpaghettiDetective#hardware-minimum-spec
"If you have an old PC with at least 2GB of memory, you will be probably be fine."

**Comment by kennethjiang** [comment]
@Ethycs sorry for the confusion. There reason why jetson needs more memory than a PC is because it shares video RAM with main RAM.

But in any case, I just changed the README to make the min requirement to 4GB. Don't think many people still have a 2GB PCs.

Not sure why `docker-compose.override.yml` seems to work for some Jetson people but not others...
