### ISSUE TITLE
The function to delete time-lapses from My Gallery

### ISSUE THREAD

**Issue by kennethjiang** [TheSpaghettiDetective/TheSpaghettiDetective#39]

**Comment by gyro2death** [comment]
Again thanks for opening this up.

I imagine this is probably not too difficult to add in so I just hope we have it soon as I have more than 10 pages already. 

For additional functionality, it might be nice to have canceled prints show up with a special border to denote them so they can be easily selected to delete if desired. Not sure if you get that information from Octoprint but it would be helpful to quickly prune the gallery.
