### ISSUE TITLE
run on boot

### ISSUE THREAD

**Issue by mcmasterp** [TheSpaghettiDetective/TheSpaghettiDetective#41]
On a ubuntu system how do we set it to run at boot?

**Comment by kennethjiang** [comment]
Good issue! Hopefully someone who is good at it can help us wrap this thing into a service?

**Comment by mcmasterp** [comment]
I found this info:



> If your docker.service enabled on system startup
> 
> $ sudo systemctl enable docker
> 
> and your services in your docker-compose.yml has
> 
> restart: always
> 
> all of the services run when you reboot your system if you run below command only once
> 
> docker-compose up -d

It seems to work for me but Ive only tested it a bit

**Comment by kennethjiang** [comment]
It sounds like an elegant solution!

**Comment by kennethjiang** [comment]
I added `restart: unless-stopped` to all services and tested it on my Mac.

Help is still needed to test it on Linux and Windows.

**Comment by mcmasterp** [comment]
I set mine to always since the machine is going to be dedicated to this and I was worried that on a restart it might interpret the system stopping it as a unless-stopped and not restarting it on reboot

**Comment by lukeslaboratory** [comment]
@kennethjiang Mine runs on boot on my windows install with docker.

**Comment by kennethjiang** [comment]
Thank you @lukeslaboratory for confirming this. It works on my Mac too. I will close this ticket. @mcmasterp please pull the latest code and all containers now should start on system reboot. Feel free to re-open this issue if it doesn't work for you.
