### ISSUE TITLE
MMU Filament Swap stops after detect/resume

### ISSUE THREAD

**Issue by allen0977** [TheSpaghettiDetective/TheSpaghettiDetective#415]
My print will be swapping filaments without issue until an incident is discovered (possible spaghetti disaster was just a misdiagnosis of infill color wipe).   When I click to "resume", the MMU is no longer able to identify the different T0-T4 extruders and completes the print using whichever filament was loaded when the incident was detected.

Another side-effect, once this happens, I cannot automatically swap extruders again until I physically reboot the printer.

MK3S+, MMU2S, RaspberryPi 3B+, SpaghettiDetective (latest)

**Comment by kennethjiang** [comment]
This sounds like a serious issue. can you reproduce this problem by manually pause the print in TSD, and resume it? No matter if it's manually paused or automatically paused for a detected failure, TSD plugin is using the same gcode for pause and resume.
