### ISSUE TITLE
[BUG] "Timelapse analyse finished" email has hardcoded URL

### ISSUE THREAD

**Issue by simonszu** [TheSpaghettiDetective/TheSpaghettiDetective#436]
**Describe the bug**
The email which is sent by TSD when an uploaded timelapse is finished has a URL to the TSD instance. This URL is pointing to "https://app.thespaghettidetective.com/prints/" even if the mail is sent by a self-hosted instance. 

**To Reproduce**
1. Set up a self hosted TSD instance
2. Configure the Site URL in the django admin interface
3. Set up email notifications
4. Upload a timelapse to be analyzed
5. Wait for the email

**Hosting environment (please complete the following information):**
 - OS: Debian Linux
 - Version: Docker build from github commit https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/commit/aa991eefdfd43c51719386689493ffbf5b1906bc
 - Hardware: A professionally hosted VPS, 6 CPU Cores, 12GB RAM

**Comment by kennethjiang** [comment]
Thank you @simonszu for submitting this bug.
