### ISSUE TITLE
How do I remove invalid links when I cannot receive heartbeat packets?

### ISSUE THREAD

**Issue by CocoaML** [TheSpaghettiDetective/TheSpaghettiDetective#454]
How do I remove invalid links when I cannot receive heartbeat packets?

code in tasks.py:
```
@periodic_task(run_every=timedelta(seconds=120))
def prune_channel_presence():
    Room.objects.prune_presences(age=120)

@periodic_task(run_every=timedelta(seconds=1200))
def prune_channel_rooms():
    Room.objects.prune_rooms()
```

The celery task can remove presence and remove room base on databases, but not remove invalid links, how can remove invalid links? For example,  a malicious program attack with invalid heartbeat.

**Comment by kennethjiang** [comment]
I'm not sure if I understand your use case. Can you give more details about the problem you are trying to address?
