### ISSUE TITLE
[BUG] Time-lapse in full screen is broken

### ISSUE THREAD

**Issue by kennethjiang** [TheSpaghettiDetective/TheSpaghettiDetective#470]
https://user-images.githubusercontent.com/779786/121604617-bc6c7500-c9ff-11eb-9fd3-4d709f66214b.mov

**Comment by dipuzyrev** [comment]
Fix https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/commit/081147545454382654c009d82f6a35b1ea277d55
