### ISSUE TITLE
[BUG] Make sure the "not watch" text are centered horizontally

### ISSUE THREAD

**Issue by kennethjiang** [TheSpaghettiDetective/TheSpaghettiDetective#471]
<img width="642" alt="Screen Shot 2021-06-10 at 3 50 37 PM" src="https://user-images.githubusercontent.com/779786/121606839-bd9fa100-ca03-11eb-9544-013c710d8f46.png">

**Comment by dipuzyrev** [comment]
Fixed https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/commit/f96d83abe3bb4d9d84776c1e98ae60b526a533ca
