### ISSUE TITLE
[BUG] Greyscale meter with overlay

### ISSUE THREAD

**Issue by kennethjiang** [TheSpaghettiDetective/TheSpaghettiDetective#472]
These colors are one-offs, other than the background and the "pointer" colors. So they don't need to be included in the theme.js file.

![image](https://user-images.githubusercontent.com/779786/121608246-63eca600-ca06-11eb-8995-edb24cc6e214.png)

**Comment by dipuzyrev** [comment]
@kennethjiang this issue requires colors adjustment, right?

**Comment by dipuzyrev** [comment]
BTW, any dynamic color have to be in `themes.js` file. I'll just leave a comment these colors are one-offs

**Comment by dipuzyrev** [comment]
Here is `#2d3e4f` color pointed as page background, but page background is `#23313f` (in dark mode, regarding to color guide). Where is the truth?)
<img width="826" alt="Screenshot 2021-06-11 at 17 13 14" src="https://user-images.githubusercontent.com/12683472/121700241-5ef82700-cad8-11eb-85ec-b9238047867d.png">

**Comment by dipuzyrev** [comment]
And are you sure about making gauge background same as page background. It will look like this <img width="1433" alt="Screenshot 2021-06-11 at 17 30 25" src="https://user-images.githubusercontent.com/12683472/121702713-cb742580-cada-11eb-8a38-706a04bd756e.png">

**Comment by dipuzyrev** [comment]
This is what I have now. First part — how it looks now in light and dark version, second — how it would look if we make gague background same as page.

https://user-images.githubusercontent.com/12683472/121705970-da100c00-cadd-11eb-853c-8ed4266b8c40.mov
