### ISSUE TITLE
bed clips false alarm

### ISSUE THREAD

**Issue by mcmasterp** [TheSpaghettiDetective/TheSpaghettiDetective#48]
I get false alarms due to the bed clips holding my glass plate on. Is it possible maybe to train the model to ignore them? I have no idea how ML modeling works so forgive me if that's a ridiculous suggestion.

**Comment by kennethjiang** [comment]
The new version of the prediction model has a lot fewer false alarms. Closing it for now but feel free to re-open it if you are still seeing excessive false alarms on bed clips @mcmasterp
