### ISSUE TITLE
[BUG] Should ignore large media file

### ISSUE THREAD

**Issue by wernight** [TheSpaghettiDetective/TheSpaghettiDetective#489]
**Describe the bug**
After a while the `web/static_build/media/tsd-timelapses/private` directory may become quite large (multi-GB). This directory is also included (i.e. not excluded from `.docker-ignore`) and so it makes building the image pretty slow. It also seems that this directly is not necessary at all.

Command to build:

```
$ docker-compose build
```

 - Is that directory useful? What for?
 - Should it be excluded in `.docker-ignore`

**Comment by kennethjiang** [comment]
Good point. Just added it to dockerignore.

This folder is to hold the time-lapse files automatically generated by TSD server.
