### ISSUE TITLE
Different ports in web/Dockerfile and docker-compose.yml

### ISSUE THREAD

**Issue by EleRas** [TheSpaghettiDetective/TheSpaghettiDetective#50]
For the container "web", the image is created from web/Dockerfile. This Dockerfile has `EXPOSE 3333`, but `docker-compose.yml` starts the service on port 3334 and defines ports "3334:3334". Wouldn't it make sense to get these differences in line and define just one port?

**Comment by kennethjiang** [comment]
Good catch! Fixed
