### ISSUE TITLE
error Failed to talk to The Spaghetti Detective server!

### ISSUE THREAD

**Issue by swormin84** [TheSpaghettiDetective/TheSpaghettiDetective#503]
Hello, I am trying to link spaghetti detective to my home IP address. I keep getting the error Failed to talk to The Spaghetti Detective server!
Make sure OctoPrint is connected to the Internet. Octoprint works locally so I assume windows is blocking TSD from accessing. Is it possible to tell why it is being blocked? I have tried a myriad/hours of solutions with no change. 
[TDS Octo.txt](https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/files/6942448/TDS.Octo.txt)

**Comment by kennethjiang** [comment]
This is not a code issue. Please go to our discord server https://discord.gg/NcZkQfj and get help there.
