### ISSUE TITLE
[Feature] Limit CPU usage of ml_api

### ISSUE THREAD

**Issue by kyngs** [TheSpaghettiDetective/TheSpaghettiDetective#531]
**Is your feature request related to a problem? Please describe.**
I have a Minecraft server running on the same machine as TSD. When I print, the server completely lags out.

**Describe the solution you'd like**
Add an option to limit the CPU usage of the ML algorithm, for example, to 300% in my case.

**Describe alternatives you've considered**
I've considered using external CPU limiting programs, but they're pretty unpractical.

**Additional context**

**Comment by kennethjiang** [comment]
This feature is actually already there, as docker has a built-in support for CPU cap.

what you can do is to create a `docker-compose.override.yml` file with the content similar to this (untested);

```
version: '2.4'

services:
  ml_api:
  cpus: 3.0
```

Again you need to test and very likely fix some syntax errors. For more info about how this works, check out https://www.baeldung.com/ops/docker-memory-limit#2-version-2-with-docker-compose

I'll close this for now. But if it somehow doesn't work for you, feel free to re-open it.
