### ISSUE TITLE
[BUG] Share feature not working

### ISSUE THREAD

**Issue by Cralost** [TheSpaghettiDetective/TheSpaghettiDetective#535]
**Describe the bug**
After opening shared link in browser there is an error saying "Not Found"

**To Reproduce**
1. open TSD 
2. click tree dots
3. Share
4. copy link
5. paste to browser

**Screenshots**

App version: v1.48.75:b119

**Comment by kennethjiang** [comment]
@Cralost Sorry for the delay. Can you try to share the feed in the web app to see if it works?

You can get help a lot more quickly by going to our discord server: https://discord.gg/hsMwGpD

**Comment by Cralost** [comment]
So I tried and I noticed that this supposes to be premium feature - I have a free plan. So maybe that is the reason (web interface stops me).

Anyway, there could be such a pop-up as well. 

Thank  you.

**Comment by kennethjiang** [comment]
Ah good point. It is a bug we overlooked. Logged it and will get it fixed in the next release.
