### ISSUE TITLE
How to Run TSD On Fluiddpi Without Putty Open?

### ISSUE THREAD

**Issue by Declan0811** [TheSpaghettiDetective/TheSpaghettiDetective#550]
Kind of a stupid question, but I went through all of the issues and such, finally enabling TSD for my Fluiddpi config, but now I don't know how to keep it running without having Putty constantly open, as every time I close it, I have to re-configure everything when opening Putty again. Any help would be appreciated, thanks!

**Comment by kennethjiang** [comment]
The best place to ask questions like this is our discord forum: https://discord.gg/NcZkQfj
