### ISSUE TITLE
Create DWC/Duet Web Control SBC plugin

### ISSUE THREAD

**Issue by Will-wastelander** [TheSpaghettiDetective/TheSpaghettiDetective#554]
https://duet3d.dozuki.com/Wiki/Duet_Web_Control_v2_and_v3_%28DWC%29_Manual
https://github.com/Duet3D/DuetSoftwareFramework/blob/master/PLUGINS.md

**Comment by Will-wastelander** [comment]
This would be a SBC based plugin.

**Comment by Will-wastelander** [comment]
@kennethjiang Let me know if you need anything for this. I've sent you a few DMs on discord.

**Comment by kennethjiang** [comment]
Ok. Thank you @Will-wastelander

**Comment by raymondh2** [comment]
Duplicate of #381
