### ISSUE TITLE
[BUG] Brief bug description here

### ISSUE THREAD

**Issue by LehmannADL** [TheSpaghettiDetective/TheSpaghettiDetective#611]
ATTEMPTED TO JOIN DISCORD ITS DOWN

ive followed your READ.ME for Linux

when i get to:

"2. Run it! Do either one of these based on what OS you are using:"

    If you are on Linux: cd TheSpaghettiDetective && sudo docker-compose up -d

i get

adam@octoprint:~$ su -
Password:
root@octoprint:~# cd TheSpaghettiDetective && sudo docker-compose up -d
sudo: docker-compose: command not found
root@octoprint:~/TheSpaghettiDetective#

COFFEE/SPONSOR FOR HELP!

**Comment by kennethjiang** [comment]
@LehmannADL thank you for sponsoring TSD! Please come to our discord channel https://discord.gg/NcZkQfj and PM me (Kenneth#0677) there. You will get helped a lot faster there.
