### ISSUE TITLE
[BUG] TSD tries to load webcam image from the wrong domain

### ISSUE THREAD

**Issue by Nordikk** [TheSpaghettiDetective/TheSpaghettiDetective#613]
I'm using TSD behind an Apache2 reverse proxy, the domain is set as tsd.xxxxx.de:443 in Django Admin
There's no webcam image showing up, so I took a look in the Chrome console, there I can see that TSD tries to connect to
`https://xxxxx.de/media/tsd-pics/snapshots/2/latest_unrotated.jpg`, 
but should be connecting to 
`https://tsd.xxxxx.de/media/tsd-pics/snapshots/2/latest_unrotated.jpg`

I'll attach screenshots.

![Screenshot 2022-04-08 153507](https://user-images.githubusercontent.com/48895515/162447028-ebc65747-e6f4-474b-acd4-a5546c2abc31.png)
![tsd](https://user-images.githubusercontent.com/48895515/162447034-faad169d-c467-4fd0-82c2-e7d342809963.png)
![Screenshot 2022-04-08 153740](https://user-images.githubusercontent.com/48895515/162448215-6077a67c-92e2-46dd-ba93-2cc22df06c0a.png)

**Comment by mcstoufer** [comment]
This issue is still here. Is it expected that this image is not supposed to be loaded and just show the alt tag?

`<img data-v-76458791="" src="http://example.com/media/tsd-pics/snapshots/1/latest_unrotated.jpg" alt="Prusa Mk3s current image" class="tagged-jpg">`

**Comment by Nordikk** [comment]
Did you set your domain name? 

You’re supposed to set it first, look at the installation instructions
