### ISSUE TITLE
[BUG] Backup instructions reference incorrect folder

### ISSUE THREAD

**Issue by TempestWales** [TheSpaghettiDetective/TheSpaghettiDetective#634]
Describe the bug
In README.md under "Backup database" the instructions do not refer to the new folder location, or how to migrate the DB having previously using an older version of TSD.

"Just make a copy of TheSpaghettiDetective/web/db.sqlite3"

The db.sqlite3 was previously in the 'TheSpaghettiDetective/web' folder however it is now in the 'TheSpaghettiDetective/backend' folder.

Migrating from the older version to the newer requires moving the file from the old web folder to the new backend.

**Comment by kennethjiang** [comment]
@TempestWales Thank you for submitting this bug and sorry for missing these migration issues for private servers. Let me know if you have run into more issues after migrating to the new version.
