### ISSUE TITLE
Adjust new print times

### ISSUE THREAD

**Issue by wwsean08** [TheSpaghettiDetective/TheSpaghettiDetective#73]
With the new print status it should be updated to show double digits for the minutes or remove the : between hours and minutes, Below is an example of it now and my two proposals for formatting:

![image](https://user-images.githubusercontent.com/839261/58743998-8350a180-83f0-11e9-828b-1a2909c411e7.png)

Proposal 1, double digits (it was too hard to modify the html for both of them at the same time before it refreshed on me):
![image](https://user-images.githubusercontent.com/839261/58744015-c1e65c00-83f0-11e9-8b9b-910add887b70.png)

Proposal 2, remove the :
![image](https://user-images.githubusercontent.com/839261/58744031-38835980-83f1-11e9-8edd-05bdc005d551.png)

Both look good to me though if we were to go proposal one I would suggest removing the hours/minutes text potentially.

**Comment by kennethjiang** [comment]
Thank you so much Sean for catching it. I'd go with option 2. Will make the change.
