### ISSUE TITLE
Notification enhancement

### ISSUE THREAD

**Issue by vr6syncro** [TheSpaghettiDetective/TheSpaghettiDetective#80]
Hello,

maybe it is possible to add more notification options.
my favourite is telegram. a simple bot  and done.

no more sms cost and better integration in many smart home systems.

**Comment by ajdavids** [comment]
Besides a telegram bot, what other notification options would be useful but not overwhelming?

**Comment by kennethjiang** [comment]
pushbullet was proposed in #52

**Comment by vr6syncro** [comment]
maybe this help u: https://github.com/python-telegram-bot/python-telegram-bot

**Comment by ajdavids** [comment]
@vr6syncro I'd already started looking at the telegram bot APIs 😃. Also going to look into the pushbullet and slack bot APIs. Waiting for permission from work to contribute before I start looking at the issue in more depth, though, Thanks for the link.

**Comment by kennethjiang** [comment]
Pushbullet is now added by #83 . Kudos to @ajdavids for his awesome PR.

@vr6syncro  Feel free to open another issue for telegram support so that we can attack them one at a time.

**Comment by flippedcracker** [comment]
I know this is closed, but I'd like to see Pushover available for notifications. 

https://pushover.net/
