### ISSUE TITLE
Webcam doesn't work

### ISSUE THREAD

**Issue by materdd** [TheSpaghettiDetective/TheSpaghettiDetective#86]
I tried to run TSD on own PC and also Octoprint is on the same PC. 
And only webcam doesn't work. I can see it on the Octoprint, but not on TSD.
I checked solutions based on the below link, but doesn't work.

https://www.thespaghettidetective.com/docs/webcam-feed-is-not-showing/

Is there any way to investigate?

Best regards, 

![image](https://user-images.githubusercontent.com/27740131/63006217-0a25fe00-beb9-11e9-83e4-77029c2f7486.png)

![image](https://user-images.githubusercontent.com/27740131/63006177-f5e20100-beb8-11e9-92f0-e4c6236debf2.png)
 
![image](https://user-images.githubusercontent.com/27740131/63032412-b931fc00-bef0-11e9-8969-4f9acf09e8ff.png)

**Comment by kennethjiang** [comment]
It looks like you didn't configure django site: https://github.com/TheSpaghettiDetective/TheSpaghettiDetective#configure-django-site

I'm closing this issue for now. But feel free to re-open it if it still doesn't work after you configure django site.
