### ISSUE TITLE
Pushover for notifications

### ISSUE THREAD

**Issue by flippedcracker** [TheSpaghettiDetective/TheSpaghettiDetective#90]
If possible, I'd like to see Pushover available for notifications.

https://pushover.net/

**Comment by Nimmsis** [comment]
I agree with this. pushover have a easy api, the ability to set priority (can even bypass do not disturb) and is fast a reliable.

**Comment by byurick** [comment]
+1 to this especially since Pushbullet no longer has an iOS app available.

**Comment by vikwin** [comment]
The feature was added with merge #357. This issue can be closed.

**Comment by kennethjiang** [comment]
Haha yes! Thank you! I'm terrible at github hygiene. :)
