### ISSUE TITLE
Support for Pushover notifications

### ISSUE THREAD

**Issue by dalgibbard** [TheSpaghettiDetective/TheSpaghettiDetective#94]
As per the title and other notification platforms; I'm personally drawn to pushover as I use it for a gazillion other platforms too (including octoprint itself).

**Comment by dalgibbard** [comment]
Whoops, this is a dupe of another issue; closing

**Comment by kennethjiang** [comment]
Right I forgot that we already have a ticket for pushover. Feel free to upvote that ticket to bump up its priority @dalgibbard
