### ISSUE TITLE
Time-Lapses Video Upside-Down

### ISSUE THREAD

**Issue by codemonkey812** [TheSpaghettiDetective/TheSpaghettiDetective#95]
I have my Pi Cam flipped both vertically and horizontally in OctoPrint. The live feed in TSD is good, but the time-lapses videos are upside-down. My username in TSD is joe.e.jamison@outlook.com if you want to review.

**Comment by barrettj** [comment]
I also have this issue (sideways), let me know if you'd like any more debugging info
